name: Deploy to Firebase Hosting

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Install Functions dependencies
        run: npm --prefix functions ci

      - name: Set Vite env vars
        run: echo "VITE_AI_API_BASE_URL=https://us-central1-cvgenius-985fd.cloudfunctions.net/aiRewrite" >> $GITHUB_ENV

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Deploy to Firebase Hosting
        run: npx firebase deploy --only hosting,functions --non-interactive --project cvgenius-985fd
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
